import type { Plugin } from '@web/dev-server-core';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

interface DemoInfo {
  componentName: string;
  tagName: string;
  demoName: string;
  url: string;
  title: string;
}

/**
 * Generate demo list HTML from custom-elements.json
 */
async function generateDemoListHTML(): Promise<string> {
  const demos: DemoInfo[] = [];
  
  try {
    const manifestPath = join(process.cwd(), 'custom-elements.json');
    const manifestContent = await readFile(manifestPath, 'utf-8');
    const manifest = JSON.parse(manifestContent);

    // Extract demos from manifest
    for (const module of manifest.modules || []) {
      for (const declaration of module.declarations || []) {
        if (declaration.customElement && declaration.demos) {
          const tagName = declaration.tagName;
          
          for (const demo of declaration.demos) {
            const componentTitle = tagName
              .replace('pfv6-', '')
              .replace(/-/g, ' ')
              .split(' ')
              .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
              .join(' ');
            
            const demoTitle = demo.name === 'index'
              ? componentTitle
              : `${componentTitle} - ${demo.name.replace(/-/g, ' ').split(' ').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}`;

            demos.push({
              componentName: tagName,
              tagName,
              demoName: demo.name,
              url: demo.url,
              title: demoTitle,
            });
          }
        }
      }
    }
  } catch (error) {
    console.warn('[demo-list-plugin] Could not read custom-elements.json:', error instanceof Error ? error.message : error);
  }

  // Sort demos by component name, then demo name
  demos.sort((a, b) => {
    if (a.componentName !== b.componentName) {
      return a.componentName.localeCompare(b.componentName);
    }
    return a.demoName.localeCompare(b.demoName);
  });

  return demos.length > 0
    ? demos.map(demo => 
        `<li><a href="${demo.url}">${demo.title}</a></li>`
      ).join('\n            ')
    : '<li>No demos available yet. Run <code>npm run compile</code> to generate the manifest.</li>';
}

/**
 * Plugin that injects a list of available demos into dev-server/index.html
 * Reads from custom-elements.json generated by CEM
 */
export function demoListPlugin(): Plugin {
  return {
    name: 'demo-list-plugin',
    async transform(context) {
      // Only inject demo list into the root index.html (served via router)
      if (context.path === '/' && context.response.is('html')) {
        const demoListHTML = await generateDemoListHTML();
        let html = context.body as string;
        html = html.replace(
          /<ul id="demo-list">[\s\S]*?<\/ul>/,
          `<ul id="demo-list">\n            ${demoListHTML}\n          </ul>`
        );
        return html;
      }
    },
  };
}
